### ISSUE TITLE
Van Der Grinten errors beyond 180 degrees

### ISSUE THREAD

**Issue by XericDesign** [tdanckaert/GCTP#1]
The Van Der Grinten code to translate x,y to lat,lon works even for values of x,y that lie beyond 180 degrees as the map repeats. However, the reverse algorithm from lat,lon to x,y will not work correctly if a longitude is outside the range of -180 to +180.

This makes it impossible to draw gridlines on a rectangular map of the world were, because of the projection, New Zealand appears twice.

**Comment by tdanckaert** [comment]
Hi, I don't maintain this library.  It's an old library used as a dependency in some other packages, and I just added a build system so it can be installed more easily (in my case, in order to build package for GNU Guix).
